package routes

import (
	"github.com/drmendoz/iglesias-backend/controllers"
	"github.com/drmendoz/iglesias-backend/middlewares"
	"github.com/gin-gonic/gin"
)

func FielRouter(r *gin.RouterGroup) {
	res := r.Group("residente")
	res.Use(middlewares.RolFielMiddleware())
	res.Use(middlewares.AuthMiddleWare())
	res.Use(middlewares.ParsingTokenFiel())
	publicacionRoutes(res)
	visitaRoutes(res)
	res.POST("/notificacion", controllers.UpdateTokenNotificacion)
	res.GET("/administrativo", controllers.GetAdministrativos)
	res.GET("/contactos", controllers.GetContactoEtapas)
	res.GET("/galeria", controllers.GetImagenGalerias)
	res.GET("/publicidades", controllers.GetPublicidads)
	res.GET("/votaciones", controllers.GetVotacions)
	res.GET("/votaciones/:id", middlewares.ValidarVoto(), controllers.GetVotacionPorId)
	res.POST("/votaciones/:id/responder", middlewares.ValidarVoto(), controllers.ResponderVotacion)
	res.GET("/alicuotas", controllers.GetAlicuotaPorFiel)
	res.GET("/alicuotas/ano", controllers.GetAlicuotaPorFielTemporal)
	res.POST("/alicuotas-pago", controllers.PagarAlicuota)
	res.POST("/cambiarContrasena", controllers.CambiarContrasenaFiel)
	res.GET("area-sociales", controllers.GetAreaSocials)
	res.GET("/reservaciones", controllers.GetReservacionesFielAreaSocial)
	res.GET("area-sociales/:id/horarios", controllers.GetHorariosPorAreaSocial)
	res.POST("area-sociales/:id/reserva", controllers.CreateReservaFiel)
	res.GET("area-sociales/:id/horarios/disponibles", controllers.GetHorarioDisponiblesAreaSocial)
	res.POST("/perfil", controllers.EditarImagenPerfilFiel)
	res.GET("/perfil", controllers.GetInformacionPerfil)
	res.GET("/camaras", controllers.GetEtapaCamaras)
	res.POST("/imagen", controllers.CrearArchivo)
	res.POST("/imagenes", controllers.CrearArchivos)
	res.GET("/categorias", controllers.GetCategoriaMarkets)
	res.GET("/suscripciones", controllers.VerificarSuscripcionFiel)
	res.POST("/suscripciones", controllers.CrearSuscripcion)
	res.DELETE("/suscripciones", controllers.AnularSuscripcion)
	res.POST("/emprendimientos", controllers.CreateEmprendimiento)
	res.GET("/emprendimientos", controllers.ObtenerEmprendimientos)
	res.GET("/mis-emprendimientos", controllers.ObtenerEmprendimientosUsuarios)
	res.GET("/residentes/:id/emprendimientos", controllers.ObtenerEmprendimientoFiel)
	res.GET("/emprendimientos/:id", controllers.ObtenerEmprendimientosPorId)
	res.PUT("/emprendimientos/:id", controllers.ActualizarEmprendimiento)
	res.DELETE("/emprendimientos/:id", controllers.DeleteEmprendimiento)
	res.POST("/cerrar-sesion", controllers.CerrarSesion)
	res.PUT("/mensajes/actualizar-respuestas/:id", controllers.ActualizarMensajeRespuestas)
	res.POST("/buzon", controllers.CreateBuzonFiel)
	res.POST("/buzon/:id_buzon/archivos", controllers.CreateArchivosBuzon)
	res.POST("/buzon/:id_buzon/responder", controllers.CreateBuzon)
	res.GET("/buzon", controllers.GetBuzonesFiel)
	res.GET("/buzon/:id_buzon", controllers.GetMensajesBuzones)
	historiaRoutes(res)
	visualizacionRoutes(res)
	tarjetaRoutes(res)
	autorizacionRoutes(res)
	autorizadoRoutes(res)
	mensajeRoutes(res)
	respuestaRoutes(res)
}
